import path from 'node:path';
import dotenv from 'dotenv';
import { z } from 'zod';

dotenv.config({ path: path.resolve(__dirname, '../../../../.env') });

const envSchema = z.object({
  NODE_ENV: z.enum(['development', 'test', 'production']).default('development'),
  PORT: z.coerce.number().default(4000),

  DATABASE_URL: z.string().min(1, 'DATABASE_URL is required'),

  JWT_SECRET: z.string().min(16, 'JWT_SECRET must be at least 16 characters'),
  JWT_EXPIRES_IN: z.string().default('8h'),
  REFRESH_TOKEN_EXPIRES_IN: z.string().default('30d'),
  BCRYPT_SALT_ROUNDS: z.coerce.number().default(12),

  STORAGE_DRIVER: z.enum(['local', 's3']).default('local'),
  STORAGE_LOCAL_PATH: z.string().default('./local-storage'),
  S3_ENDPOINT: z.string().optional(),
  S3_REGION: z.string().default('us-east-1'),
  S3_BUCKET: z.string().default('blue-carbon-evidence'),
  S3_ACCESS_KEY_ID: z.string().optional(),
  S3_SECRET_ACCESS_KEY: z.string().optional(),
  S3_FORCE_PATH_STYLE: z
    .string()
    .default('true')
    .transform((v) => v === 'true'),

  ML_SERVICE_URL: z.string().default('http://localhost:8010'),
  ML_SERVICE_TIMEOUT_MS: z.coerce.number().default(30000),

  DUPLICATE_PROXIMITY_METERS: z.coerce.number().default(50),
  DUPLICATE_TIME_WINDOW_HOURS: z.coerce.number().default(48),

  FABRIC_ENABLED: z
    .string()
    .default('false')
    .transform((v) => v === 'true'),
  FABRIC_CHANNEL_NAME: z.string().default('mrvchannel'),
  FABRIC_CHAINCODE_NAME: z.string().default('mrv-contract'),
  FABRIC_MSP_ID: z.string().default('Org1MSP'),
  FABRIC_PEER_ENDPOINT: z.string().default('localhost:7051'),
  FABRIC_PEER_HOST_ALIAS: z.string().default('peer0.org1.example.com'),
  // Paths to crypto material generated by network.sh (see network/README.md), resolved
  // relative to the repo root regardless of process.cwd() - same reasoning as
  // STORAGE_LOCAL_PATH's fix (see storageService.ts).
  FABRIC_TLS_CERT_PATH: z
    .string()
    .default(
      './network/fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt'
    ),
  FABRIC_CERT_DIRECTORY_PATH: z
    .string()
    .default(
      './network/fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts/'
    ),
  FABRIC_KEY_DIRECTORY_PATH: z
    .string()
    .default(
      './network/fabric-samples/test-network/organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/'
    ),

  CORS_ORIGIN: z.string().default('http://localhost:3000'),

  RATE_LIMIT_WINDOW_MS: z.coerce.number().default(900000),
  RATE_LIMIT_MAX_REQUESTS: z.coerce.number().default(300),
});

const parsed = envSchema.safeParse(process.env);

if (!parsed.success) {
  // eslint-disable-next-line no-console
  console.error('Invalid environment configuration:', parsed.error.flatten().fieldErrors);
  throw new Error('Invalid environment configuration. See errors above.');
}

export const env = parsed.data;
export type Env = typeof env;
